# Generated by Django 2.2.26 on 2022-01-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_dislike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
